import Link from 'next/link';
import { ArrowDown,ArrowUpRight } from 'lucide-react';
import { PublicHeader,Footer,Glass } from '@/components/brand';
export default function Home() {return <><PublicHeader/><main id="main">
 <section className="hero"><div className="hero-art"><Glass/></div><div className="hero-pills"><Link href="/matrix">Матрица компетенций</Link><Link href="/tracks">Профессиональные треки</Link><Link href="/materials">Полезные материалы</Link><Link href="/app">Мой план развития</Link></div><div className="hero-caption"><span className="eyebrow light">ДЛЯ ДИЗАЙН-КОМАНДЫ</span><h1>Дизайн —<br/>пространство<br/>роста</h1><p>Понимать свой уровень.<br/>Выбирать направление. Двигаться дальше.</p></div><a className="hero-down" href="#explore" aria-label="Подробнее о платформе"><ArrowDown size={30}/></a><span className="hero-index">01 / РАЗВИТИЕ</span></section>
 <section id="explore" className="section"><div className="section-heading"><span className="eyebrow">ОБЩИЙ ЯЗЫК ДЛЯ РАЗВИТИЯ</span><h2>Не просто оценка.<br/>Понятный следующий шаг.</h2><p>Матрица помогает увидеть сильные стороны, обсудить ожидания и выбрать конкретные точки роста вместе с руководителем.</p></div>
 <div className="tile-grid"><Link className="tile tile-wide" href="/matrix"><h3>Изучить матрицу<br/>компетенций</h3><span className="tile-caption">Четыре области. Общие критерии.</span><span className="tile-icon blue"><Glass small/></span><ArrowUpRight className="tile-arrow"/></Link><Link className="tile tile-wide" href="/tracks"><h3>Найти своё<br/>направление</h3><span className="tile-caption">Профессиональные и управленческий треки</span><span className="tile-icon orange">→</span><ArrowUpRight className="tile-arrow"/></Link><Link className="tile tile-wide" href="/app"><h3>Собрать личный<br/>план развития</h3><span className="tile-caption">Одна общая цель и одна цель трека</span><span className="tile-icon purple">→</span><ArrowUpRight className="tile-arrow"/></Link><Link className="tile" href="/materials"><h3>Полезные<br/>материалы</h3><span className="tile-icon blue">✳</span><ArrowUpRight className="tile-arrow"/></Link><a className="tile" href="#process"><h3>Как проходит<br/>review</h3><span className="tile-icon orange">↔</span><ArrowUpRight className="tile-arrow"/></a></div></section>
 <section className="section methodology"><div className="section-heading"><span className="eyebrow">МАТРИЦА КОМПЕТЕНЦИЙ</span><h2>Уровень — это ориентир.<br/>Развитие — это путь.</h2></div><div className="method-grid"><div className="method-main"><span className="big-number">1—4</span><p>Каждая компетенция описана на четырёх уровнях. Сравнивайте конкретные критерии, а не впечатления.</p><Link href="/matrix" className="text-link">Посмотреть критерии <ArrowUpRight size={18}/></Link></div><div className="method-text"><h3>Junior → Middle → Senior</h3><p>Уровни отдельных компетенций складываются в общий ориентир по грейду. Четыре области имеют одинаковый вес. «Н/П» и пустые ответы не снижают средний балл.</p><h3>Экспертиза и управление</h3><p>Senior-эксперт углубляет профессиональную практику. Senior-тимлид развивает людей и работу команды. Экспертный и управленческий треки подтверждаются отдельно.</p><div className="note">Итоговый балл помогает калибровке и обсуждению. Он не является автоматическим решением о повышении.</div><p className="small muted">Методология на этой странице основана на задании; точные критерии и формулы будут сверены с исходной таблицей.</p></div></div></section>
 <section id="process" className="section process"><div className="section-heading"><span className="eyebrow">ОТ ОЦЕНКИ К ДЕЙСТВИЯМ</span><h2>Четыре шага.<br/>Один общий план.</h2></div><div className="process-grid">{[['01','Самооценка','Выберите уровни, добавьте комментарии и примеры работ.'],['02','Взгляд руководителя','Руководитель даёт независимую оценку. После публикации вы видите расхождения.'],['03','Разговор и review','Обсудите ожидания, согласуйте итоговые оценки и подтвердите результат.'],['04','Развитие','Выберите до двух целей на 3–6 месяцев. Отмечайте действия и собирайте подтверждения прогресса.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="closing"><h2>Следующий шаг<br/>начинается с вас.</h2><Link className="button white" href="/login">Перейти в кабинет <ArrowUpRight size={18}/></Link></section>
 </main><Footer/></>}
