'use client';
import { useState } from 'react';
import { AREA_NAMES,TRACK_NAMES,MATERIAL_TYPES,roleNames,type Matrix,type Material,type User } from '@/lib/model';
import type { WorkspaceData } from '@/lib/data';
import { Field,Feedback,useAction,ActionButton } from './forms';
import { formatDate } from './workspace';
export function Admin({data}:{data:WorkspaceData}) {
 const [tab,setTab]=useState('users');const [editingUser,setEditingUser]=useState<(User&{active:boolean})|undefined>();const [editingMaterial,setEditingMaterial]=useState<Material|undefined>();const [matrix,setMatrix]=useState<Matrix|undefined>(data.matrices[0]?.data);
 const tabs:Record<string,string>={users:'Пользователи',cycles:'Циклы оценки',matrix:'Матрица и треки',materials:'Материалы',audit:'Журнал изменений'};
 return <><div className="workspace-heading"><h2>Общие правила.<br/>Живой контент.</h2><p>Управление командой, методологией и материалами без изменения кода.</p></div><div className="grid-4">{[[data.users.filter(u=>u.active).length,'Активных пользователей'],[data.cycles.filter(c=>!c.archived).length,'Открытых циклов'],[data.matrices.filter(m=>m.published).length,'Версий методологии'],[data.materials.length,'Материалов']].map(([n,label])=><div className="panel" key={label}><span className="label">{label}</span><span className="metric" style={{fontSize:36}}>{n}</span></div>)}</div><div className="tabs">{Object.entries(tabs).map(([key,title])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{title}</button>)}</div>
 {tab==='users'&&<><div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Руководитель</th><th>Доступ</th><th></th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td>{u.name}<br/><span className="small muted">{u.email}</span></td><td>{roleNames[u.role]}</td><td>{data.users.find(m=>m.id===u.manager_id)?.name??'—'}</td><td>{u.active?'Активен':'Отключён'}</td><td><button className="button light" onClick={()=>setEditingUser(u)}>Изменить</button></td></tr>)}</tbody></table></div><div className="panel white"><h3>{editingUser?'Изменить пользователя':'Добавить пользователя'}</h3><UserForm key={editingUser?.id??'new'} existing={editingUser} users={data.users}/>{editingUser&&<button className="logout" onClick={()=>setEditingUser(undefined)}>Перейти к добавлению нового</button>}</div></>}
 {tab==='cycles'&&<><CycleForm data={data}/>{data.cycles.map(c=><article className="panel white" key={c.id}><div className="panel-header"><h3>{c.title}</h3><span className="badge">{c.archived?'Архив':'Открыт'}</span></div><p>Review: {formatDate(c.review_date)} · Участников: {data.assessments.filter(a=>a.cycle_id===c.id).length}</p>{!c.archived&&<><CycleDateForm cycle={c}/><ActionButton action="archive" payload={{id:c.id}}>Архивировать завершённый цикл</ActionButton></>}</article>)}</>}
 {tab==='matrix'&&<><div className="note">Используемая в циклах версия неизменяема. Редактирование создаёт новую версию и не пересчитывает прошлые оценки. Формулировки берутся только из исходной таблицы.</div>{data.matrices.length>0&&<div className="tabs">{data.matrices.map(m=><button key={m.id} onClick={()=>setMatrix(m.data)}>{m.title} · {m.published?'опубликована':'черновик'}</button>)}</div>}<MatrixForm key={JSON.stringify(matrix)} existing={matrix}/></>}
 {tab==='materials'&&<><div className="panel white"><h3>{editingMaterial?'Редактировать материал':'Новый материал'}</h3><MaterialForm key={editingMaterial?.id??'new'} existing={editingMaterial} matrices={data.matrices.map(m=>m.data)}/>{editingMaterial&&<button className="logout" onClick={()=>setEditingMaterial(undefined)}>Добавить другой материал</button>}</div><div className="table-wrap"><table><thead><tr><th>Материал</th><th>Тип и доступ</th><th></th></tr></thead><tbody>{data.materials.map(m=><tr key={m.id}><td>{m.title}<br/><span className="small muted">{m.category}</span></td><td>{MATERIAL_TYPES[m.type]} · {m.internal?'Внутренний':'Публичный'}</td><td><button className="button light" onClick={()=>setEditingMaterial(m)}>Изменить</button></td></tr>)}</tbody></table></div></>}
 {tab==='audit'&&<><p className="small muted">Последние 100 событий. Итоговые оценки и изменения целей сохраняют прежние значения. Удаление журнала через интерфейс недоступно.</p><div className="table-wrap"><table><thead><tr><th>Дата</th><th>Автор</th><th>Изменение</th><th>Причина и значения</th></tr></thead><tbody>{data.audit.map(event=><tr key={event.id}><td>{formatDate(new Date(event.created_at).toISOString())}</td><td>{data.users.find(u=>u.id===event.actor_id)?.name??'Начальная настройка'}</td><td>{event.entity} · {event.action}{event.new_data?.kind==='final'&&<><br/><span className="badge orange">Итоговая оценка</span></>}</td><td>{event.reason||'—'}<details><summary>До / после</summary><pre className="json-preview">{JSON.stringify({before:event.old_data,after:event.new_data},null,2)}</pre></details></td></tr>)}</tbody></table></div></>}
 </>
}
function UserForm({existing,users}:{existing?:User&{active:boolean};users:(User&{active:boolean})[]}) {
 const a=useAction();return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.run('user',{...(existing?{id:existing.id}:{}),name:f.get('name'),email:f.get('email'),role:f.get('role'),direction:f.get('direction'),manager_id:f.get('manager')||null,active:f.get('active')==='on',...(f.get('password')?{password:f.get('password')}:{})});}}><div className="field-row"><Field label="Имя"><input name="name" defaultValue={existing?.name} required maxLength={300}/></Field><Field label="Почта"><input name="email" type="email" defaultValue={existing?.email} required/></Field></div><div className="field-row"><Field label="Роль"><select name="role" defaultValue={existing?.role??'designer'}>{Object.entries(roleNames).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></Field><Field label="Руководитель"><select name="manager" defaultValue={existing?.manager_id??''}><option value="">Не назначен</option>{users.filter(u=>u.role==='manager'&&u.active&&u.id!==existing?.id).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field></div><Field label="Должность / направление"><input name="direction" defaultValue={existing?.direction} maxLength={300}/></Field><Field label={existing?'Новый пароль (если нужно изменить)':'Временный пароль'} hint="Не менее 12 символов. Передайте сотруднику безопасным способом."><input type="password" name="password" autoComplete="new-password" required={!existing} minLength={12} maxLength={128}/></Field><label className="check-row"><input type="checkbox" name="active" defaultChecked={existing?.active??true}/>Активный доступ</label><button className="button dark" disabled={a.busy}>Сохранить пользователя</button><Feedback {...a}/></form>
}
function CycleDateForm({cycle}:{cycle:{id:string;review_date:string}}){const a=useAction();return <form style={{marginBottom:24}} onSubmit={e=>{e.preventDefault();a.run('cycleDate',{id:cycle.id,review_date:new FormData(e.currentTarget).get('date')});}}><Field label="Изменить плановую дату review" hint="Дата уже проведённой встречи остаётся в истории."><input name="date" type="date" defaultValue={cycle.review_date.slice(0,10)} required/></Field><button className="button outline" disabled={a.busy}>Сохранить дату</button><Feedback {...a}/></form>}
function CycleForm({data}:{data:WorkspaceData}) {
 const a=useAction();return <div className="panel white"><h3>Новый цикл оценки</h3>{!data.matrices.some(m=>m.published)?<p className="muted">Сначала перенесите и опубликуйте методологию в разделе «Матрица и треки».</p>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.run('cycle',{title:f.get('title'),matrix_id:f.get('matrix'),review_date:f.get('date'),user_ids:f.getAll('users')});}}><Field label="Название цикла"><input name="title" required placeholder="Например, осенний review" maxLength={300}/></Field><div className="field-row"><Field label="Версия матрицы"><select name="matrix">{data.matrices.filter(m=>m.published).map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></Field><Field label="Дата review"><input required type="date" name="date"/></Field></div><h4>Участники</h4>{data.users.filter(u=>u.active).map(u=><label className="check-row" key={u.id}><input type="checkbox" name="users" value={u.id}/>{u.name} · {roleNames[u.role]}</label>)}<button className="button dark" disabled={a.busy}>Создать цикл и карточки</button><Feedback {...a}/></form>}</div>
}
function MaterialForm({existing,matrices}:{existing?:Material;matrices:Matrix[]}) {
 const a=useAction();const comps=[...new Map(matrices.flatMap(m=>[...m.areas,...m.tracks].flatMap(g=>g.competencies)).map(c=>[c.id,c])).values()];
 return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.run('material',{...(existing?{id:existing.id}:{}),title:f.get('title'),description:f.get('description'),url:f.get('url'),type:f.get('type'),category:f.get('category'),difficulty:f.get('difficulty'),author:f.get('author'),tags:String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),internal:f.get('internal')==='on',competency_ids:f.getAll('competencies')});}}><Field label="Название"><input name="title" required defaultValue={existing?.title} maxLength={300}/></Field><Field label="Краткое описание"><textarea name="description" required defaultValue={existing?.description} maxLength={10000}/></Field><Field label="Ссылка"><input name="url" type="url" required defaultValue={existing?.url}/></Field><div className="field-row"><Field label="Тип"><select name="type" defaultValue={existing?.type??'article'}>{Object.entries(MATERIAL_TYPES).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></Field><Field label="Область / трек"><input name="category" defaultValue={existing?.category} list="material-categories"/><datalist id="material-categories">{[...AREA_NAMES,...TRACK_NAMES].map(c=><option key={c} value={c}/>)}</datalist></Field></div><div className="field-row"><Field label="Сложность"><select name="difficulty" defaultValue={existing?.difficulty??'Любой уровень'}>{['Любой уровень','Начальный','Средний','Продвинутый'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Автор / источник"><input name="author" defaultValue={existing?.author}/></Field></div><Field label="Теги через запятую"><input name="tags" defaultValue={existing?.tags.join(', ')}/></Field><label className="check-row"><input name="internal" type="checkbox" defaultChecked={existing?.internal}/>Внутренний материал: только после входа</label>{comps.length>0&&<details className="accordion"><summary>Связать с компетенциями</summary>{comps.map(c=><label className="check-row" key={c.id}><input type="checkbox" name="competencies" value={c.id} defaultChecked={existing?.competency_ids.includes(c.id)}/>{c.name}</label>)}</details>}<button className="button dark" disabled={a.busy}>Сохранить материал</button><Feedback {...a}/></form>
}
function blankMatrix():Matrix{return {areas:AREA_NAMES.map((name,i)=>({id:`area-${i+1}`,name,competencies:Array.from({length:i===0?4:3},(_,j)=>({id:`a${i+1}-c${j+1}`,name:'',description:'',levels:['','','',''] as [string,string,string,string]}))})),tracks:TRACK_NAMES.map((name,i)=>({id:`track-${i+1}`,name,management:i===4,competencies:[{id:`t${i+1}-c1`,name:'',description:'',levels:['','','',''] as [string,string,string,string]}]}))}}
function MatrixForm({existing}:{existing?:Matrix}) {
 const [matrix,setMatrix]=useState<Matrix>(existing??blankMatrix());const [title,setTitle]=useState('');const [source,setSource]=useState('https://docs.google.com/spreadsheets/d/1FnSxdW8QRjgPHfXXgJHUwXQs1noFjdHgRmRxGT64hDQ/edit');const [verified,setVerified]=useState(false);const [published,setPublished]=useState(true);const action=useAction();
 function update(group:'areas'|'tracks',i:number,j:number,field:'name'|'description'|'level',value:string,level=0){setMatrix(old=>({...old,[group]:old[group].map((g,index)=>index!==i?g:{...g,competencies:g.competencies.map((c,k)=>k!==j?c:field==='level'?{...c,levels:c.levels.map((l,n)=>n===level?value:l)}:{...c,[field]:value})})} as Matrix));}
 return <form noValidate style={{marginTop:30}} onSubmit={e=>{e.preventDefault();action.run('matrix',{title,source_note:source,data:matrix,published,source_verified:verified});}}><h3>{existing?'Создать следующую версию':'Перенести исходную матрицу'}</h3><p className="small muted">Заполните оригинальные названия, пояснения и описания уровней. Поля намеренно пустые: источник ещё не импортирован. Формулы пока соответствуют заданию и требуют сверки по XLSX.</p><Field label="Название версии"><input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={300}/></Field><Field label="Источник и примечание о проверке"><textarea required value={source} onChange={e=>setSource(e.target.value)}/></Field>{(['areas','tracks'] as const).map(group=>matrix[group].map((g,i)=><details className="accordion" key={g.id}><summary>{g.name} · {g.competencies.length} компетенций</summary>{g.competencies.map((c,j)=><div className="panel" key={c.id}><span className="small muted">{c.id}</span><Field label="Название компетенции из источника"><input required value={c.name} onChange={e=>update(group,i,j,'name',e.target.value)}/></Field><Field label="Пояснение из источника (если есть)"><textarea value={c.description} onChange={e=>update(group,i,j,'description',e.target.value)}/></Field>{c.levels.map((l,n)=><Field key={n} label={`Уровень ${n+1} — точное описание`}><textarea required value={l} onChange={e=>update(group,i,j,'level',e.target.value,n)}/></Field>)}{group==='tracks'&&g.competencies.length>1&&<button type="button" className="button outline" onClick={()=>setMatrix(old=>({...old,tracks:old.tracks.map((t,index)=>index===i?{...t,competencies:t.competencies.filter(x=>x.id!==c.id)}:t)}))}>Удалить из новой версии</button>}</div>)}{group==='tracks'&&<button type="button" className="button light" onClick={()=>setMatrix(old=>({...old,tracks:old.tracks.map((t,index)=>index===i?{...t,competencies:[...t.competencies,{id:`t${i+1}-${crypto.randomUUID().slice(0,8)}`,name:'',description:'',levels:['','','','']}]}:t)}))}>Добавить компетенцию трека</button>}</details>))}<label className="check-row"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)} required/>Формулировки и методика сверены с исходной таблицей</label><label className="check-row"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Опубликовать для команды и гостей</label><button className="button dark" disabled={action.busy||!verified}>{action.busy?'Сохраняем…':'Сохранить новую версию'}</button><Feedback {...action}/></form>
}
