'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight,Bookmark } from 'lucide-react';
import { type Matrix,type Material,type Competency,MATERIAL_TYPES } from '@/lib/model';
import { useAction,Feedback } from './forms';
export function SourceEmpty(){return <div className="empty"><span className="badge gray">Каталог готовится</span><h3 style={{marginTop:20}}>Точные критерии — из нашей матрицы</h3><p>Компетенции и описания уровней появятся после переноса исходной таблицы. Пока здесь нет опубликованной версии методологии.</p><Link className="text-link" href="/">Как устроено развитие <ArrowUpRight size={18}/></Link></div>}
export function CompetencyCard({c,area}:{c:Competency;area:string}){const [left,setLeft]=useState(1);return <details className="accordion"><summary>{c.name}</summary><p className="small muted">{area}</p>{c.description&&<p>{c.description}</p>}<label className="field">Сравнить соседние уровни<select value={left} onChange={e=>setLeft(Number(e.target.value))}><option value={1}>Уровни 1 и 2</option><option value={2}>Уровни 2 и 3</option><option value={3}>Уровни 3 и 4</option></select></label><div className="level-list">{[left,left+1].map(n=><div className="level" key={n}><span>Уровень {n}</span><p style={{whiteSpace:'pre-wrap'}}>{c.levels[n-1]}</p></div>)}</div><details><summary>Все четыре уровня</summary><div className="level-list">{c.levels.map((l,i)=><div className="level" key={i}><span>Уровень {i+1}</span><p style={{whiteSpace:'pre-wrap'}}>{l}</p></div>)}</div></details><p style={{marginTop:20}}><Link className="text-link" href={`/matrix/${c.id}`}>Открыть карточку →</Link></p></details>}
export function MatrixCatalog({matrix}:{matrix:Matrix|null}){
 const [query,setQuery]=useState('');const [area,setArea]=useState('all');if(!matrix)return <SourceEmpty/>;
 const matches=matrix.areas.filter(a=>area==='all'||a.id===area).map(a=>({...a,competencies:a.competencies.filter(c=>`${c.name} ${c.description}`.toLowerCase().includes(query.toLowerCase()))}));
 return <><div className="filters"><input className="input" aria-label="Поиск компетенций" placeholder="Найти компетенцию" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input" aria-label="Область" value={area} onChange={e=>setArea(e.target.value)}><option value="all">Все области</option>{matrix.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>{matches.every(a=>!a.competencies.length)&&<div className="empty">Ничего не найдено. Попробуйте другое название.</div>}{matches.map(a=>a.competencies.length>0&&<section key={a.id} style={{marginTop:40}}><h2 style={{fontSize:30}}>{a.name}</h2>{a.competencies.map(c=><CompetencyCard key={c.id} c={c} area={a.name}/>)}</section>)}</>
}
export function MaterialsCatalog({materials,favorites=[],signedIn=false}:{materials:Material[];favorites?:string[];signedIn?:boolean}) {
 const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [type,setType]=useState('all');const [onlyFavorite,setOnlyFavorite]=useState(false);const a=useAction();
 const filtered=materials.filter(m=>(category==='all'||m.category===category)&&(type==='all'||m.type===type)&&(!onlyFavorite||favorites.includes(m.id))&&`${m.title} ${m.description} ${m.tags.join(' ')} ${m.author}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="filters"><input className="input" aria-label="Поиск материалов" placeholder="Название, тема или тег" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input" aria-label="Категория" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Все категории</option>{[...new Set(materials.map(m=>m.category).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select><select className="input" aria-label="Тип материала" value={type} onChange={e=>setType(e.target.value)}><option value="all">Все типы</option>{Object.entries(MATERIAL_TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{signedIn&&<button className="button outline" aria-pressed={onlyFavorite} onClick={()=>setOnlyFavorite(!onlyFavorite)}>{onlyFavorite?'✓ Избранное':'Избранное'}</button>}</div><Feedback {...a}/><p className="small muted" role="status">Найдено: {filtered.length}</p>{!filtered.length?<div className="empty"><h3>Пока нет материалов</h3><p>Измените фильтры или вернитесь позже. Базу знаний пополняет администратор.</p></div>:<div className="material-grid">{filtered.map(m=><article className="material-card" key={m.id}><span className="eyebrow">{MATERIAL_TYPES[m.type]??m.type}{m.internal?' · ВНУТРЕННИЙ':''}</span><h3>{m.title}</h3><p>{m.description}</p><p className="small">{m.author} · {m.difficulty}</p><div className="tags">{m.tags.map(t=><span key={t}>{t}</span>)}</div><div className="material-bottom"><a href={m.url} target="_blank" rel="noopener noreferrer">Открыть материал →</a>{signedIn?<button className={`icon-button ${favorites.includes(m.id)?'selected':''}`} aria-label={`${favorites.includes(m.id)?'Убрать из избранного':'Добавить в избранное'}: ${m.title}`} aria-pressed={favorites.includes(m.id)} disabled={a.busy} onClick={()=>a.run('favorite',{material_id:m.id,enabled:!favorites.includes(m.id)})}><Bookmark size={16}/></button>:<Link href="/login" className="icon-button" aria-label="Войти для добавления в избранное"><Bookmark size={16}/></Link>}</div><p className="small muted" style={{margin:'12px 0 0'}}>Добавлено {new Date(m.created_at).toLocaleDateString('ru-RU')}</p></article>)}</div>}</>
}
