'use client';
import { useState } from 'react';
import { allCompetencies,GOAL_STATUSES,type Assessment,type Goal,type User,type Material } from '@/lib/model';
import { ActionButton,Field,Feedback,useAction } from './forms';
import { formatDate } from './workspace';
export function Goals({assessments,user,materials}:{assessments:Assessment[];user:User;materials:Material[]}) {
 const eligible=assessments.filter(a=>a.status>=4);
 if(!eligible.length)return <div className="empty"><span className="badge">После review</span><h3 style={{marginTop:18}}>Выберите две точки роста</h3><p>После обсуждения оценки вы сможете согласовать одну цель общей матрицы и одну цель профессионального трека на 3 или 6 месяцев.</p></div>;
 return <section style={{marginTop:36}}><div className="workspace-heading"><span className="eyebrow">ПЛАН НА 3–6 МЕСЯЦЕВ</span><h2 style={{marginTop:16}}>Меньше целей.<br/>Больше движения.</h2><p>Выбор всегда остаётся за сотрудником и руководителем. Изменение содержания требует повторного согласования.</p></div>{eligible.map(a=><section key={a.id}><h3>{a.title} · {a.user_name}</h3>{a.goals.map(g=><GoalCard key={g.id} goal={g} a={a} user={user} materials={materials}/>)}{(['general','track'] as const).map(source=>!a.goals.some(g=>g.source===source)&&<details className="accordion" key={source}><summary>Выбрать цель {source==='general'?'общей матрицы':'профессионального трека'}</summary><GoalForm source={source} a={a} materials={materials}/></details>)}</section>)}</section>
}
function GoalForm({source,a,materials,existing}:{source:'general'|'track';a:Assessment;materials:Material[];existing?:Goal}) {
 const comps=(source==='general'?a.data.areas:a.data.tracks.filter(t=>[a.primary_track,a.additional_track].includes(t.id))).flatMap(x=>x.competencies).filter(c=>{const r=a.ratings.find(r=>r.kind==='final'&&r.competency_id===c.id);return r?.value!=null&&r.value<4;}).sort((aComp,bComp)=>{
  const gap=(id:string)=>{const s=a.ratings.find(r=>r.kind==='self'&&r.competency_id===id)?.value;const m=a.ratings.find(r=>r.kind==='manager'&&r.competency_id===id)?.value;return s!=null&&m!=null?Math.abs(s-m):0;};return gap(bComp.id)-gap(aComp.id);
 });
 const [chosen,setChosen]=useState(existing?.competency_id??comps[0]?.id??'');const c=comps.find(c=>c.id===chosen);
 const current=a.ratings.find(r=>r.kind==='final'&&r.competency_id===chosen)?.value??1;
 const [target,setTarget]=useState(existing?.target_level??Math.min(4,current+1));const [months,setMonths]=useState<3|6>(existing?.months??3);
 const [result,setResult]=useState(existing?.expected_result??'');const [criteria,setCriteria]=useState(existing?.success_criteria??'');const [actions,setActions]=useState(existing?.actions.map(a=>a.text).join('\n')??'');const [ids,setIds]=useState(existing?.material_ids??[]);const action=useAction();
 if(!comps.length)return <div className="note">{source==='track'&&!a.primary_track?'Сначала выберите профессиональный трек.':'Пока нет компетенций с согласованной числовой оценкой ниже 4. Заполните итоговые ответы после review.'}</div>;
 return <form onSubmit={e=>{e.preventDefault();action.run('goal',{...(existing?{id:existing.id,revision:existing.revision}:{}),assessment_id:a.id,source,competency_id:chosen,current_level:current,target_level:target,months,expected_result:result,success_criteria:criteria,actions:actions.split('\n').map(s=>s.trim()).filter(Boolean).map(text=>({text,done:false})),material_ids:ids});}}>
 <p className="small muted">Предложения расположены по величине расхождения. Это рекомендации, а не назначенные цели.</p><Field label="Компетенция"><select value={chosen} onChange={e=>{setChosen(e.target.value);const rating=a.ratings.find(r=>r.kind==='final'&&r.competency_id===e.target.value);setTarget(Math.min(4,(rating?.value??1)+1));}}>{comps.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><div className="field-row"><Field label={`Текущий уровень: ${current}. Целевой уровень`}><select value={target} onChange={e=>setTarget(Number(e.target.value))}>{[2,3,4].filter(n=>n>current).map(n=><option key={n} value={n}>{n} — {c?.levels[n-1]}</option>)}</select></Field><Field label="Горизонт развития"><select value={months} onChange={e=>setMonths(Number(e.target.value) as 3|6)}><option value={3}>3 месяца</option><option value={6}>6 месяцев</option></select></Field></div><div className="level-description">Целевой уровень: {c?.levels[target-1]}</div><Field label="Ожидаемый результат"><textarea required value={result} onChange={e=>setResult(e.target.value)} maxLength={10000}/></Field><Field label="Конкретные действия" hint="От 2 до 4 действий, каждое на отдельной строке"><textarea required value={actions} onChange={e=>setActions(e.target.value)}/></Field><Field label="Критерии успешного выполнения"><textarea required value={criteria} onChange={e=>setCriteria(e.target.value)} maxLength={10000}/></Field><h4>Полезные материалы</h4>{materials.length?materials.map(m=><label className="check-row" key={m.id}><input type="checkbox" checked={ids.includes(m.id)} onChange={e=>setIds(e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/>{m.title}</label>):<p className="small muted">Пока нет доступных материалов.</p>}<button className="button dark" disabled={action.busy}>{action.busy?'Сохраняем…':existing?'Сохранить и согласовать заново':'Создать цель для согласования'}</button><Feedback {...action}/></form>
}
function GoalCard({goal:g,a,user,materials}:{goal:Goal;a:Assessment;user:User;materials:Material[]}) {
 const action=useAction();const [comment,setComment]=useState(a.user_id===user.id?g.employee_comment:g.manager_comment);const [checkpoint,setCheckpoint]=useState('');const [link,setLink]=useState('');const [status,setStatus]=useState(g.status);const [newDate,setNewDate]=useState('');
 const c=allCompetencies(a.data).find(c=>c.id===g.competency_id);const approved=g.employee_approved&&g.manager_approved;const done=g.actions.filter(x=>x.done).length;
 return <article className="goal-card"><div className="panel-header"><span className="badge">{g.source==='general'?'Общая матрица':'Профессиональный трек'}</span><span className="small muted">{GOAL_STATUSES[g.status]}</span></div><h3>{c?.name??'Компетенция'}</h3><p className="muted">Уровень {g.current_level} → {g.target_level} · {g.months} месяцев · До {formatDate(g.due_date)}</p><p style={{whiteSpace:'pre-wrap'}}>{g.expected_result}</p><div className="approval-row"><span className="badge gray">Сотрудник: {g.employee_approved?'согласовано':'ожидается'}</span><span className="badge gray">Руководитель: {g.manager_approved?'согласовано':'ожидается'}</span></div>{!(a.user_id===user.id?g.employee_approved:g.manager_approved)&&<ActionButton action="goalApprove" payload={{id:g.id,revision:g.revision}}>Согласовать цель</ActionButton>}<div className="progress-track"><span style={{width:`${done/g.actions.length*100}%`}}/></div><p className="small muted">{done} из {g.actions.length} действий · {Math.round(done/g.actions.length*100)}%</p><h4>Действия</h4>{g.actions.map((item,i)=><label className="check-row" key={i}><input type="checkbox" checked={item.done} disabled={!approved||action.busy} onChange={e=>action.run('goalProgress',{id:g.id,revision:g.revision,actions:g.actions.map((x,index)=>index===i?e.target.checked:x.done),status:'active'})}/><span>{item.text}</span></label>)}<h4>Критерии успеха</h4><p style={{whiteSpace:'pre-wrap'}}>{g.success_criteria}</p>{g.material_ids.length>0&&<><h4>Материалы</h4>{materials.filter(m=>g.material_ids.includes(m.id)).map(m=><p key={m.id}><a className="text-link" href={m.url} target="_blank" rel="noopener noreferrer">{m.title} →</a></p>)}</>}<h4>Промежуточные отметки</h4>{g.checkpoints.length?g.checkpoints.map((point,i)=><p key={i}><span className="small muted">{formatDate(point.date)}</span><br/>{point.text}{point.url&&<> · <a className="text-link" href={point.url} target="_blank" rel="noopener noreferrer">Подтверждение →</a></>}</p>):<p className="small muted">Пока нет отметок.</p>}
 {approved&&<form onSubmit={async e=>{e.preventDefault();const ok=await action.run('goalProgress',{id:g.id,revision:g.revision,status,comment,...(status==='postponed'?{new_due_date:newDate}:{}),...(checkpoint?{checkpoint:{text:checkpoint,...(link?{url:link}:{})}}:{})});if(ok){setCheckpoint('');setLink('');}}}><div className="field-row"><Field label="Новая отметка"><input value={checkpoint} onChange={e=>setCheckpoint(e.target.value)} maxLength={300}/></Field><Field label="Ссылка-подтверждение"><input type="url" value={link} onChange={e=>setLink(e.target.value)}/></Field></div><Field label={a.user_id===user.id?'Комментарий сотрудника':'Комментарий руководителя'}><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={10000}/></Field><div className="field-row"><Field label="Статус цели"><select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(GOAL_STATUSES).map(([key,title])=><option value={key} key={key}>{title}</option>)}</select></Field>{status==='postponed'&&<Field label="Новый срок" hint="Потребуется повторное согласование"><input required type="date" min={g.due_date.slice(0,10)} value={newDate} onChange={e=>setNewDate(e.target.value)}/></Field>}</div><button className="button dark" disabled={action.busy}>Сохранить прогресс</button></form>}
 <Feedback {...action}/>{g.employee_comment&&<p>Сотрудник: {g.employee_comment}</p>}{g.manager_comment&&<p>Руководитель: {g.manager_comment}</p>}<details className="accordion"><summary>Редактировать содержание цели</summary><p className="small muted">Сохранение сбросит подтверждения и отметки выполнения действий. Предыдущие значения сохранятся в журнале.</p><GoalForm source={g.source} a={a} materials={materials} existing={g}/></details></article>
}
