'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { LayoutDashboard,ClipboardList,TrendingUp,History,Users,BookOpen,Settings,Menu,ArrowUpRight } from 'lucide-react';
import { Brand } from './brand';
import { MaterialsCatalog } from './catalog';
import { ActionButton,Field,Feedback,useAction } from './forms';
import { AREA_NAMES,STATUSES,calculate,allCompetencies,roleNames,type User,type Assessment,type Competency,type Rating,type Material } from '@/lib/model';
import type { WorkspaceData } from '@/lib/data';
import { Goals } from './goals';
import { Admin } from './admin';
const nav=[['','Мой обзор',LayoutDashboard],['assessment','Оценка',ClipboardList],['development','Развитие',TrendingUp],['history','История',History],['materials','Материалы',BookOpen]] as const;
function EmptyCycle(){return <div className="empty"><span className="badge">Пока нет активного цикла</span><h3 style={{marginTop:20}}>Начнём с общей матрицы</h3><p>Администратор опубликует методику и назначит цикл оценки. После этого здесь появится ваша карточка и следующие действия.</p><Link className="button dark" href="/matrix">Изучить матрицу →</Link></div>}
export function Workspace({data,section,selected}:{data:WorkspaceData;section:string;selected?:Assessment}) {
 const router=useRouter();const [menu,setMenu]=useState(false);const [logoutError,setLogoutError]=useState('');
 const user=data.user;const own=data.assessments.filter(a=>a.user_id===user.id);const active=own.find(a=>a.status<6);
 const titles:Record<string,string>={'':'Мой обзор',assessment:'Оценка',development:'План развития',history:'История оценки',materials:'Полезные материалы',team:'Команда',admin:'Управление'};
 return <div className="app-shell"><aside className={`app-sidebar ${menu?'menu-open':''}`}><Brand/><button className="mobile-menu" aria-expanded={menu} aria-controls="app-nav" onClick={()=>setMenu(!menu)}><Menu size={17}/> Меню</button><nav id="app-nav" className={`app-nav ${menu?'open':''}`} aria-label="Кабинет">{nav.map(([href,label,Icon])=><Link key={href} href={'/app'+(href?'/'+href:'')} aria-current={section===href?'page':undefined}><Icon size={16}/>{label}</Link>)}{user.role!=='designer'&&<Link href="/app/team" aria-current={section==='team'?'page':undefined}><Users size={16}/>Команда</Link>}{user.role==='admin'&&<Link href="/app/admin" aria-current={section==='admin'?'page':undefined}><Settings size={16}/>Управление</Link>}</nav><div className="sidebar-bottom"><Link className="text-link" href="/matrix">Общая матрица <ArrowUpRight size={14}/></Link><div className="sidebar-user"><strong>{user.name}</strong><span className="muted">{roleNames[user.role]}</span><br/><button className="logout" onClick={async()=>{try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw new Error();router.push('/login');router.refresh();}catch{setLogoutError('Не удалось выйти. Повторите попытку.');}}}>Выйти из кабинета</button><Feedback error={logoutError}/></div></div></aside>
 <main id="main" className="app-main"><div className="page-banner"><h1>{titles[section]??'Карточка оценки'}</h1><span className="small">{user.name}</span></div>
 {section===''&&<Dashboard user={user} active={active} data={data}/>}
 {section==='assessment'&&(selected??active?<AssessmentView key={(selected??active)!.id} a={(selected??active)!} user={user} materials={data.materials}/>:<EmptyCycle/>)}
 {section==='development'&&<Goals assessments={own} user={user} materials={data.materials}/>}
 {section==='history'&&<HistoryView assessments={own}/>}
 {section==='materials'&&<MaterialsCatalog materials={data.materials} favorites={data.favorites} signedIn/>}
 {section==='team'&&<Team data={data}/>}
 {section==='admin'&&<Admin data={data}/>}
 </main></div>
}
function Dashboard({user,active,data}:{user:User;active?:Assessment;data:WorkspaceData}) {
 const result=active?calculate(active.data,active.ratings,active.status>=4?'final':'self'):null;
 const diffs=active?.data.areas.flatMap(a=>a.competencies).map(c=>({c,self:active.ratings.find(r=>r.kind==='self'&&r.competency_id===c.id),manager:active.ratings.find(r=>r.kind==='manager'&&r.competency_id===c.id)})).filter(x=>x.self?.value&&x.manager?.value&&x.self.value!==x.manager.value)??[];
 const goals=data.assessments.filter(a=>a.user_id===user.id).flatMap(a=>a.goals).filter(g=>!['completed','cancelled'].includes(g.status));
 const materialIds=new Set(goals.flatMap(g=>g.material_ids));const recommendations=data.materials.filter(m=>materialIds.has(m.id));
 return <><div className="workspace-heading"><span className="eyebrow">ВАШЕ ПРОФЕССИОНАЛЬНОЕ РАЗВИТИЕ</span><h2 style={{marginTop:16}}>Двигаемся дальше,<br/>{user.name.split(' ')[0]}.</h2><p>{user.direction||'Дизайн-команда'} · {active?.data.tracks.find(t=>t.id===active.primary_track)?.name??'Трек ещё не выбран'}</p></div>
 {!active?<EmptyCycle/>:<><div className="panel sky"><div className="panel-header"><span className="eyebrow">СЛЕДУЮЩИЙ ШАГ</span><span className="badge gray">{STATUSES[active.status]}</span></div><h3>{['Заполните самооценку','Самооценка отправлена. Ожидайте обратную связь.','Руководитель готовит оценку','Подготовьтесь к обсуждению','Проверьте согласованный итог','Согласуйте цели развития'][active.status]}</h3><p>{active.title} · Review {formatDate(active.review_date)}</p><Link className="button dark" href={`/app/assessment/${active.id}`}>Открыть карточку <ArrowUpRight size={16}/></Link></div>
 <div className="grid-2"><div className="panel"><span className="label">{active.status>=5?'Подтверждённый результат':active.status>=4?'Согласование итога':'Предварительная самооценка'}</span><span className="metric">{result?.score?.toFixed(2).replace('.',',')??'—'}<small style={{fontSize:18}}> / 4</small></span><p>{result?.grade??'Недостаточно числовых оценок'}{result?.percent!==null&&result?.percent!==undefined?` · ${result.percent.toFixed(1)}%`:''}</p><span className="small muted">Ориентир для калибровки, а не автоматическое повышение.</span></div><div className="panel"><span className="label">Заполненность общей матрицы</span><span className="metric">{result?.count??0}<small style={{fontSize:18}}> / 13</small></span><div className="progress-track"><span style={{width:`${(result?.count??0)/13*100}%`}}/></div><p>Для результата: 11 числовых оценок и минимумы по каждой области.</p></div></div></>}
 <h3>Четыре области развития</h3><div className="grid-4">{AREA_NAMES.map((name,i)=><div className="panel" key={name}><span className="area-label">{name}</span><span className="metric" style={{fontSize:34}}>{result?.areas[i]?.average?.toFixed(2).replace('.',',')??'—'}</span><span className="small muted">{result?`${result.areas[i].count} ответов · минимум ${result.areas[i].required}`:'Пока нет оценки'}</span></div>)}</div>
 <div className="grid-2"><div className="panel white"><div className="panel-header"><h3>Точки обсуждения</h3><span className="badge">{diffs.length}</span></div>{diffs.length?diffs.slice(0,4).map(x=><p key={x.c.id}>{x.c.name}<br/><span className="small muted">Вы: {x.self!.value} · Руководитель: {x.manager!.value}</span></p>):<p className="muted">После публикации оценки руководителя здесь появятся расхождения.</p>}</div><div className="panel white"><h3>Ближайшие цели</h3>{goals.length?goals.slice(0,2).map(g=><p key={g.id}>Уровень {g.current_level} → {g.target_level} · до {formatDate(g.due_date)}<br/><span className="small muted">{g.actions.filter(a=>a.done).length} из {g.actions.length} действий</span></p>):<p className="muted">Выберите до двух целей после review — одну из общей матрицы и одну из трека.</p>}<Link className="text-link" href="/app/development">К плану развития →</Link></div></div>
 <div className="panel"><h3>Материалы для ваших целей</h3>{recommendations.length?recommendations.map(m=><p key={m.id}><a className="text-link" href={m.url} target="_blank" rel="noopener noreferrer">{m.title} →</a></p>):<p className="muted">Рекомендации появятся после привязки материалов к целям.</p>}<Link className="text-link" href="/app/materials">Открыть базу знаний →</Link></div></>
}
export function formatDate(value:string|null|undefined){return value?new Date(value.slice(0,10)+'T12:00:00Z').toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'}):'Дата не назначена'}
function RatingForm({c,rating,kind,a,user}:{c:Competency;rating?:Rating;kind:Rating['kind'];a:Assessment;user:User}) {
 const editable=kind==='self'?a.user_id===user.id&&a.status===0:user.role!=='designer'&&(kind==='manager'?[1,2].includes(a.status):[4,5].includes(a.status));
 const [value,setValue]=useState(rating?.answer==='na'?'na':rating?.value?.toString()??'');const [comment,setComment]=useState(rating?.comment??'');const [evidence,setEvidence]=useState(rating?.evidence.join('\n')??'');const [reason,setReason]=useState('');const action=useAction();
 const title=kind==='self'?'Самооценка':kind==='manager'?'Руководитель':'Согласованный итог';
 if(kind==='manager'&&user.role==='designer'&&a.status<3)return <div className="rating-column"><h4>{title}</h4><p className="muted">Оценка станет доступна после публикации.</p></div>;
 return <form className="rating-column" onSubmit={e=>{e.preventDefault();action.run('rating',{assessment_id:a.id,revision:a.revision,competency_id:c.id,kind,answer:value==='na'?'na':value?'rated':'unanswered',value:value&&value!=='na'?Number(value):null,comment,evidence:evidence.split('\n').map(s=>s.trim()).filter(Boolean)},reason);}}><h4>{title}</h4>{editable?<Field label="Уровень"><select value={value} onChange={e=>setValue(e.target.value)}><option value="">Не выбран</option>{c.levels.map((l,i)=><option value={i+1} key={i}>{i+1} — {l}</option>)}<option value="na">Н/П — не применимо</option></select></Field>:<span className="badge">{rating?.answer==='na'?'Н/П':rating?.value??'Нет оценки'}</span>}{value&&value!=='na'&&<div className="level-description">{value} — {c.levels[Number(value)-1]}</div>}{value==='na'&&<p className="small muted">Не применимо · не входит в среднее</p>}{editable?<><Field label="Комментарий"><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={10000}/></Field><Field label="Примеры работ" hint="Одна HTTP(S)-ссылка на строку"><textarea value={evidence} onChange={e=>setEvidence(e.target.value)}/></Field>{kind==='final'&&a.status===5&&<Field label="Причина исправления"><input required value={reason} onChange={e=>setReason(e.target.value)}/></Field>}<button className="button dark" disabled={action.busy}>{action.busy?'Сохраняем…':'Сохранить ответ'}</button><Feedback {...action}/></>:<><p style={{marginTop:16,whiteSpace:'pre-wrap'}}>{rating?.comment||'Комментария пока нет'}</p>{rating?.evidence.map(url=><p key={url} style={{overflowWrap:'anywhere'}}><a className="text-link" href={url} target="_blank" rel="noopener noreferrer">Подтверждение →</a></p>)}</>}</form>
}
function AssessmentView({a,user,materials}:{a:Assessment;user:User;materials:Material[]}) {
 const [area,setArea]=useState('all');const [review,setReview]=useState(a.review_comment);const [primary,setPrimary]=useState(a.primary_track??'');const [additional,setAdditional]=useState(a.additional_track??'');const save=useAction();
 const result=calculate(a.data,a.ratings,a.status>=4?'final':'self');const groups=[...a.data.areas,...a.data.tracks.filter(t=>[a.primary_track,a.additional_track].includes(t.id))];const canManage=user.role!=='designer';const nextLabels=['Отправить руководителю','Начать оценку','Опубликовать оценку','Зафиксировать проведённое review','Подтвердить итог цикла','Завершить и перенести в историю'];
 return <><div className="workspace-heading"><span className="eyebrow">{a.title}</span><h2 style={{marginTop:16}}>{a.user_name}</h2><p>Review: {formatDate(a.review_date)} · {STATUSES[a.status]}</p></div><div className="status-steps" aria-label="Этапы оценки">{STATUSES.map((s,i)=><span key={s} className={i===a.status?'current':''} aria-current={i===a.status?'step':undefined}>{i+1}. {s}</span>)}</div><div className="assessment-summary"><div className="panel-header"><div><span className="badge">{a.status>=4?'Согласованный итог':'Предварительная самооценка'}</span><p style={{margin:'15px 0 0'}}>{result.score===null?'Недостаточно оценок':`${result.score.toFixed(2)} / 4 · ${result.grade} · ${result.percent!.toFixed(1)}%`} · {result.count}/13 числовых ответов</p></div></div>{!result.complete&&<p className="small muted">{result.areas.map(x=>`${x.name}: ${x.count}, минимум ${x.required}`).join(' · ')}</p>}<p className="small muted">Грейд — ориентир для калибровки. Профессиональный и управленческий уровень подтверждаются отдельно.</p>{a.status===3&&canManage&&<Field label="Итоги встречи review"><textarea value={review} onChange={e=>setReview(e.target.value)}/></Field>}{a.review_comment&&a.status>=4&&<p style={{whiteSpace:'pre-wrap'}}>Review: {a.review_comment}</p>}<div className="approval-row">{a.status>=4&&<><span className="badge gray">Сотрудник: {a.employee_confirmed?'подтверждено':'ожидается'}</span><span className="badge gray">Руководитель: {a.manager_confirmed?'подтверждено':'ожидается'}</span></>}</div><div className="form-actions">{a.status===4&&<ActionButton action="confirm" payload={{assessment_id:a.id,revision:a.revision}} disabled={!result.complete}>Подтвердить согласованные оценки</ActionButton>}{a.status<6&&((a.status===0&&a.user_id===user.id)||(a.status>0&&canManage))&&<ActionButton action="transition" payload={{assessment_id:a.id,revision:a.revision,target:a.status+1,review_comment:review}} disabled={a.status===4&&!(a.employee_confirmed&&a.manager_confirmed)}>{nextLabels[a.status]}</ActionButton>}</div></div>
 <details className="accordion"><summary>Профессиональное направление</summary><form onSubmit={e=>{e.preventDefault();save.run('tracks',{assessment_id:a.id,revision:a.revision,primary:primary||null,additional:additional||null});}}><div className="field-row"><Field label="Основной трек"><select value={primary} onChange={e=>setPrimary(e.target.value)} disabled={a.status>=5}><option value="">Не выбран</option>{a.data.tracks.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field><Field label="Дополнительный трек"><select value={additional} onChange={e=>setAdditional(e.target.value)} disabled={a.status>=5}><option value="">Не выбран</option>{a.data.tracks.filter(t=>t.id!==primary).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field></div>{a.status<5&&<button className="button dark" disabled={save.busy}>Сохранить направление</button>}<Feedback {...save}/></form></details>
 <div className="tabs" aria-label="Области оценки"><button aria-pressed={area==='all'} onClick={()=>setArea('all')}>Все области</button>{groups.map(g=><button key={g.id} aria-pressed={area===g.id} onClick={()=>setArea(g.id)}>{g.name}</button>)}</div>{groups.filter(g=>area==='all'||g.id===area).map(g=><section key={g.id}><h2 style={{fontSize:28,marginTop:30}}>{g.name}</h2>{g.competencies.map(c=>{const self=a.ratings.find(r=>r.competency_id===c.id&&r.kind==='self');const manager=a.ratings.find(r=>r.competency_id===c.id&&r.kind==='manager');const gap=self?.value!=null&&manager?.value!=null?self.value-manager.value:null;return <article className="competency" key={c.id}><h3>{c.name}</h3>{c.description&&<p className="competency-details">{c.description}</p>}{gap!==null&&<p className="small">Расхождение: {gap>0?'+':''}{gap} · Самооценка {self!.value}, руководитель {manager!.value}</p>}<div className="rating-columns">{(['self','manager','final'] as const).map(kind=><RatingForm key={`${c.id}-${kind}`} c={c} rating={a.ratings.find(r=>r.competency_id===c.id&&r.kind===kind)} kind={kind} a={a} user={user}/>)}</div></article>})}</section>)}
 {a.status>=4&&<Goals assessments={[a]} user={user} materials={materials}/>}
 </>
}
function HistoryView({assessments}:{assessments:Assessment[]}) {
 const history=assessments.filter(a=>a.status===6);if(!history.length)return <div className="empty"><h3>Здесь будет история роста</h3><p>Завершённые циклы, результаты по областям и прошлые цели появятся после первого review.</p></div>;
 return <>{history.map((a,i)=>{const result=calculate(a.data,a.ratings,'final');const previous=history[i+1]?calculate(history[i+1].data,history[i+1].ratings,'final'):null;return <article className="panel white" key={a.id}><div className="panel-header"><h3>{a.title}</h3><span className="badge">{formatDate(a.review_date)}</span></div><span className="metric">{result.score?.toFixed(2)??'—'} <small style={{fontSize:18}}>{result.grade}</small></span>{previous?.score!==null&&previous?.score!==undefined&&result.score!==null&&<p>Изменение к предыдущему циклу: {(result.score-previous.score).toFixed(2)}</p>}<div className="grid-4">{result.areas.map((r,index)=><p key={r.id}><span className="small muted">{r.name}</span><br/>{r.average?.toFixed(2)??'—'}{previous?.areas[index]?.average!=null&&r.average!=null&&<span className="small muted"> · Δ {(r.average-previous.areas[index].average!).toFixed(2)}</span>}</p>)}</div><p>Целей: {a.goals.length} · Выполнено: {a.goals.filter(g=>g.status==='completed').length}</p>{(a.history_goals??a.goals).map(g=><p className="small muted" key={g.id}>{allCompetencies(a.data).find(c=>c.id===g.competency_id)?.name} · {g.current_level} → {g.target_level} · {a.goals.find(current=>current.id===g.id)?.status==='completed'?'Выполнено':'Сохранено в плане'}</p>)}<Link className="text-link" href={`/app/assessment/${a.id}`}>Посмотреть завершённый review →</Link></article>})}</>
}
function Team({data}:{data:WorkspaceData}) {
 const employees=data.users.filter(u=>u.id!==data.user.id&&u.role==='designer');
 return <><div className="workspace-heading"><h2>Команда в движении.</h2><p>Статусы, точки обсуждения и ближайшие сроки. Без рейтингов и сравнения людей.</p></div>{!employees.length?<div className="empty"><h3>Пока нет назначенных сотрудников</h3><p>Администратор назначает руководителя в разделе пользователей.</p></div>:<div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Цикл и статус</th><th>Точки обсуждения</th><th>План развития</th><th>Review</th></tr></thead><tbody>{employees.map(u=>{const a=data.assessments.find(a=>a.user_id===u.id&&a.status<6)??data.assessments.find(a=>a.user_id===u.id);const gaps=a?.data.areas.flatMap(ar=>ar.competencies).filter(c=>{const s=a.ratings.find(r=>r.competency_id===c.id&&r.kind==='self');const m=a.ratings.find(r=>r.competency_id===c.id&&r.kind==='manager');return s?.value!=null&&m?.value!=null&&Math.abs(s.value-m.value)>=2;}).length??0;return <tr key={u.id}><td><strong>{u.name}</strong><br/><span className="small muted">{u.direction}</span></td><td>{a?<Link className="text-link" href={`/app/assessment/${a.id}`}>{a.title}<br/>{STATUSES[a.status]} →</Link>:'Цикл не назначен'}</td><td>{gaps?`${gaps} крупных расхождений`:'—'}</td><td>{a?.goals.length?a.goals.map(g=><p className="small" key={g.id}>{g.employee_approved&&g.manager_approved?'Согласовано':'Нужно согласование'}<br/>До {formatDate(g.due_date)}</p>):'Цели не выбраны'}</td><td>{formatDate(a?.review_date)}</td></tr>})}</tbody></table></div>}</>
}
